
database:
    # database name
    url: sqlite:///./csvdb

data:
    
    # The location of the sequencing sample metadata. This containes information
    # about the indexed, sample names, genome used, sequencing ID
    sequencing_info: '/ifs/projects/adam/combat_project/database_data/samples-metadata.tsv'