#
# pipeline_cell_qc.py configuration file
# =========================================
#

# General options
# ---------------

# Project name
projectname: scRNAseq cell QC

# Author
author: COMBATOxford


# compute resource options
# ------------------------
resources:
    # number of job threads/slots
    threads: 6


# Calculate QC metrics
# ------------------------
calculate_qc_metrics:
    # Calculate the percentage of UMIs for genesets provided ------------------------
    # Header-less, two-column tsv file with genesets to evaluate, one geneset per row. 
    # First column: name of geneset; Second column: name of the file containing the geneset. 
    # The file containing the geneset must be a header-less, one-column tsv file with gene names (one per row).")
    # Default = none
    # E.g = genesets.tsv
    geneset_file: none 
    
    # Label barcodes as True/False based on whether they are part or not of a list of barcodes provided ----------
    # Header-less, two-column, gzipped tsv.gz file containing barcodes to label as 'True', one barcode per row.
    # The name of the file will be used to set the column name in the output dataframe ('.tsv.gz' will be removed from the final name).
    # First column: barcode name in the format UMI-1, e.g AAACCTGAGAGGTACC-1.
    # Second column: sample or channel id name.
    # If a barcode is included in the file, it will be labeled as 'True', otherwise as 'False'
    # Default = none
    # E.g = cellranger_filtered.tsv.gz
    barcodes_to_label_as_True: none


# Calculate doublet scores with scrublet
# --------------------------------------
scrublet:
    # The expected fraction of transcriptomes that are doublets, typically 0.05-0.1.
    # Results are not particularly sensitive to this parameter.
    # https://github.com/AllonKleinLab/scrublet/blob/master/examples/scrublet_basics.ipynb
    expected_doublet_rate: 0.06

    # Subset the scrublet run to a list of 'white-listed' barcodes.
    # For each sample this list needs to be provided in the input_samples.tsv as a column
    # named whitelist.
    subset: 0
    # Additional parameters for scrublet's function 'scrub_doublets'
    # Default parmeters from https://github.com/AllonKleinLab/scrublet/blob/master/examples/scrublet_basics.ipynb
    min_counts: 2
    min_cells: 3
    min_gene_variability_pctl: 85
    n_prin_comps: 30
    
