#
# Pipeline pipeline_geneticdemultiplexing.py configuration file
# ==================================================
#

# General options
# ---------------

# Project name
project_name: P190381

# Copyright statement
copyright: ?

# Note on input files
# ----------------------------------------


# General options to control where to write
# ----------------------------------------
general:
  #explicitly set the path to save files to. /path/to/dir/where/you/want/output
  rundir: /well/combat/users/ypz321/testpipeline

# Options for channel demultiplexing task
# ----------------------------------------
channel:
  # number of threads to use for channel parsing
  numcpu: 2
  # the folder where the results of vireo, demuxlet are.
  # generally smth like /well/singlecell/P*******/10X-demux
  basedir: /well/combat/users/ypz321/testpipeline/project_dir
  # what demultiplexing you want to parse. These are independent folders in the ${basedir} one
  demultiplexing: demuxlet2,demuxlet,vireo
  # name of the sample==channel==pool that is being demultiplexed
  sample: 726070_GX06,726070_GX18
  # just subset the plotting of specific diagnostic on some param*alg combinations.
  subset: vireo-gtf,vireo-known,vireo-wgs
  


# Options for project parsing task
# ----------------------------------------
project:
  # number of threads to use
  numcpu: 1
  # the name of the projet results folder 
  project: P190381
  #this is the present dir where the sample dir were created for the channel parsing task
  basedir: /well/combat/users/ypz321/testpipeline/test2
  # which channels belong to this group and you want to plot them together?
  sampledir: 726070_GX06,726070_GX18
  # just subset the plotting of specific diagnostic on some param*alg combinations. 
  # can be different than the first subset specified in the per channel task
  subset: demuxlet-gtf-0.1,demuxlet-wgs-0.1,vireo-gtf,vireo-known,vireo-wgs
   

