
database:
    # central database name
    centraldb: sqlite:////gfs/work/cesarmp/ox_samsons_singlecell_db/ox_ssinglecell_db

    # local database name
    localdb: sqlite:////gfs/work/cesarmp/csvdb
        # Metadata of this database/dataset/experiment
        # name: descriptive string (e.g. mrc_earlyarthritis_synovium_20210331)
        name: mrc_earlyarthritis_synovium_20210331
        # Specie: Homo sapiens, Mus musculus
        specie: Homo sapiens
        # Tissue
        tissue: synovium
        # Modality: GEX, GEXADT GEXADTVDJ
        modality: GEXADT
        # cell_isolation: short description
        cell_isolation: microfluidic
        # library: 5', 3', full
        library: 5'

